"""init

Revision ID: a8f5b4811ad4
Revises: f1a2b3c4d5e6
Create Date: 2026-03-26 00:04:44.281488

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f5b4811ad4'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('examId', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_questions_examId'), 'questions', ['examId'], unique=False)
    op.create_foreign_key(None, 'questions', 'exams', ['examId'], ['examId'])
    op.drop_column('questions', 'test_id')
    op.add_column('students', sa.Column('examId', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_students_examId'), 'students', ['examId'], unique=False)
    op.create_foreign_key(None, 'students', 'exams', ['examId'], ['examId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_examId'), table_name='students')
    op.drop_column('students', 'examId')
    op.add_column('questions', sa.Column('test_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_examId'), table_name='questions')
    op.drop_column('questions', 'examId')
    # ### end Alembic commands ###
