"""add_created_by_to_exams

Revision ID: d5e6f7a8b9c0
Revises: c4d5e6f7a8b9
Create Date: 2026-03-25 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e6f7a8b9c0'
down_revision = 'c4d5e6f7a8b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('createdBy', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_exams_created_by_users', 'exams', 'users', ['createdBy'], ['userId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_exams_created_by_users', 'exams', type_='foreignkey')
    op.drop_column('exams', 'createdBy')
    # ### end Alembic commands ###
