"""create_users_table

Revision ID: a097babf817f
Revises: 
Create Date: 2026-03-02 09:54:20.279593

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a097babf817f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('role', sa.Enum('ROLE_ADMIN', 'ROLE_STUDENT', name='roleenum'), nullable=False),
    sa.Column('user_image', sa.Text(), nullable=False),
    sa.Column('user_login', sa.Integer(), nullable=False),
    sa.Column('examcredits', sa.Integer(), server_default='7', nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('longqa',
    sa.Column('longqa_qid', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('qid', sa.String(length=25), nullable=False),
    sa.Column('q', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('longqa_qid')
    )
    op.create_index(op.f('ix_longqa_uid'), 'longqa', ['uid'], unique=False)
    op.create_table('longtest',
    sa.Column('longtest_qid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('ans', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('longtest_qid')
    )
    op.create_index(op.f('ix_longtest_uid'), 'longtest', ['uid'], unique=False)
    op.create_table('practicalqa',
    sa.Column('pracqa_qid', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('qid', sa.String(length=25), nullable=False),
    sa.Column('q', sa.Text(), nullable=False),
    sa.Column('compiler', sa.SmallInteger(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('pracqa_qid')
    )
    op.create_index(op.f('ix_practicalqa_uid'), 'practicalqa', ['uid'], unique=False)
    op.create_table('practicaltest',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('qid', sa.String(length=25), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('executed', sa.String(length=125), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_practicaltest_uid'), 'practicaltest', ['uid'], unique=False)
    op.create_table('proctoring_log',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('voice_db', sa.Integer(), server_default='0', nullable=False),
    sa.Column('img_log', sa.Text(), nullable=False),
    sa.Column('user_movements_updown', sa.SmallInteger(), nullable=False),
    sa.Column('user_movements_lr', sa.SmallInteger(), nullable=False),
    sa.Column('user_movements_eyes', sa.SmallInteger(), nullable=False),
    sa.Column('phone_detection', sa.SmallInteger(), nullable=False),
    sa.Column('person_status', sa.SmallInteger(), nullable=False),
    sa.Column('log_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_proctoring_log_email'), 'proctoring_log', ['email'], unique=False)
    op.create_index(op.f('ix_proctoring_log_uid'), 'proctoring_log', ['uid'], unique=False)
    op.create_table('questions',
    sa.Column('questions_uid', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('qid', sa.String(length=25), nullable=False),
    sa.Column('q', sa.Text(), nullable=False),
    sa.Column('a', sa.String(length=100), nullable=False),
    sa.Column('b', sa.String(length=100), nullable=False),
    sa.Column('c', sa.String(length=100), nullable=False),
    sa.Column('d', sa.String(length=100), nullable=False),
    sa.Column('ans', sa.String(length=10), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('questions_uid')
    )
    op.create_index(op.f('ix_questions_uid'), 'questions', ['uid'], unique=False)
    op.create_table('students',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('qid', sa.String(length=25), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_students_uid'), 'students', ['uid'], unique=False)
    op.create_table('studenttestinfo',
    sa.Column('stiid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('time_left', sa.Time(), nullable=False),
    sa.Column('completed', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('stiid')
    )
    op.create_index(op.f('ix_studenttestinfo_uid'), 'studenttestinfo', ['uid'], unique=False)
    op.create_table('teachers',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=75), nullable=False),
    sa.Column('start', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('show_ans', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('neg_marks', sa.Integer(), nullable=False),
    sa.Column('calc', sa.SmallInteger(), nullable=False),
    sa.Column('proctoring_type', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_index(op.f('ix_teachers_uid'), 'teachers', ['uid'], unique=False)
    op.create_table('window_estimation_log',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('window_event', sa.SmallInteger(), nullable=False),
    sa.Column('transaction_log', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('wid')
    )
    op.create_index(op.f('ix_window_estimation_log_uid'), 'window_estimation_log', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_window_estimation_log_uid'), table_name='window_estimation_log')
    op.drop_table('window_estimation_log')
    op.drop_index(op.f('ix_teachers_uid'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_studenttestinfo_uid'), table_name='studenttestinfo')
    op.drop_table('studenttestinfo')
    op.drop_index(op.f('ix_students_uid'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_questions_uid'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_proctoring_log_uid'), table_name='proctoring_log')
    op.drop_index(op.f('ix_proctoring_log_email'), table_name='proctoring_log')
    op.drop_table('proctoring_log')
    op.drop_index(op.f('ix_practicaltest_uid'), table_name='practicaltest')
    op.drop_table('practicaltest')
    op.drop_index(op.f('ix_practicalqa_uid'), table_name='practicalqa')
    op.drop_table('practicalqa')
    op.drop_index(op.f('ix_longtest_uid'), table_name='longtest')
    op.drop_table('longtest')
    op.drop_index(op.f('ix_longqa_uid'), table_name='longqa')
    op.drop_table('longqa')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
